### ISSUE TITLE
manager crashes when using new refresh product downloads feature

### ISSUE THREAD

**Issue by CuddleBear92** [AcrylicShrimp/dlsite-manager#7] opened 2023-08-15 12:22 UTC
Manager crashes when using new refresh product downloads feature.
This happens no matter if there is new additions or not in the refresh. it will crash no matter what it seems.

I find no logs? maybe a log feature might be handy for tracelogs to help with reporting?

**Comment by AcrylicShrimp** [comment] 2023-08-15 13:15
Um, I cannot reproduce it. Can you let me know when it's crashing? It runs product refreshing before scanning existing downloads. Which stage do you have problem?

Anyway, it's good to have those environment/crash logging systems. I'll make a plan to add some.

**Comment by CuddleBear92** [comment] 2023-08-15 19:56
so i get the overlay that its updating my titles, 0/88 and so on. it finishes that up it seems as it does 88/88 then it closes the overlay for a split sec and crashes on me.

**Comment by AcrylicShrimp** [comment] 2023-08-21 15:55
Did you managed your problem? I tried many times to reproduce the issue you described, but I failed. I cannot reproduce it.

**Comment by AcrylicShrimp** [comment] 2024-03-02 18:36
I'll close this issue, please re-open it or file new one if you need.

**Closed by AcrylicShrimp** 2024-03-02 18:36 UTC
Labels: bug, enhancement, help wanted
